### ISSUE TITLE
tarball cleanup

### ISSUE THREAD

**Issue by JAORMX** [metal-toolbox/helm-tar-update#2]
Currently, the workflow will only download a new tarball while leaving the old one in place. It would be ideal for the workflow to clean up after itself and remove unused dependencies.

**Comment by andy-v-h** [comment]
Is there a reason this doesn't do `helm dependency update`, which does the cleanup?

**Comment by JAORMX** [comment]
@andy-v-h there is no reason; at the time I couldn't get it properly working with that command... But I also didn't try too hard. Feel free to submit a PR.
